# Generated by Django 4.2.7 on 2023-12-15 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='guid',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='deneme',
        ),
    ]
